// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfq3QwUhRQr7Alj43m5uQ8rDoM-r26Moc',
    appId: '1:192885778627:web:3e7384db1f9294638a9a76',
    messagingSenderId: '192885778627',
    projectId: 'pmob-a2f19',
    authDomain: 'pmob-a2f19.firebaseapp.com',
    storageBucket: 'pmob-a2f19.appspot.com',
    measurementId: 'G-Z1GT34GS4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdLzfijZEF8enJJLIDtDZe83kUPwr_QI8',
    appId: '1:192885778627:android:1f62326eb1dd7c788a9a76',
    messagingSenderId: '192885778627',
    projectId: 'pmob-a2f19',
    storageBucket: 'pmob-a2f19.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfq3QwUhRQr7Alj43m5uQ8rDoM-r26Moc',
    appId: '1:192885778627:web:666897dd5e12d22c8a9a76',
    messagingSenderId: '192885778627',
    projectId: 'pmob-a2f19',
    authDomain: 'pmob-a2f19.firebaseapp.com',
    storageBucket: 'pmob-a2f19.appspot.com',
    measurementId: 'G-QV1CBXZK6L',
  );
}
